(define (calc a op b)
  (if (eq? op "+")
      (+ a b)
      (if (eq? op "-")
          (- a b)
          (if (eq? op "*")
              (* a b)
              (if (eq? op "/")
                  (if (eq? b 0)
                      (begin
                        (print "Error: division by zero")
                        0)
                      (div a b))
                  (begin
                    (print "Unknown operator")
                    0))))))

(define (simple-calc-example)
  (begin
    (display "Calculator Examples:")
    (display " ")
    (display "5 + 3 = ")
    (print (calc 5 "+" 3))
    (display "10 - 4 = ")
    (print (calc 10 "-" 4))
    (display "6 * 7 = ")
    (print (calc 6 "*" 7))
    (display "20 / 4 = ")
    (print (calc 20 "/" 4))
    (display "10 / 0 = ")
    (calc 10 "/" 0)))

(simple-calc-example)
