name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies and Haskell Stack
        run: |
          echo "Installing required build tools..."
          sudo apt-get update
          sudo apt-get install -y build-essential make curl

          echo "Installing Haskell Stack..."
          if ! command -v stack &> /dev/null; then
            curl -sSL https://get.haskellstack.org/ | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
            export PATH="$HOME/.local/bin:$PATH"
          else
            echo "Stack already installed"
          fi

          echo "Verifying Stack installation..."
          stack --version

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('**/*.yaml') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build project
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make re
          echo "Build completed successfully on branch ${{ github.ref_name }}"
