name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Haskell environment
        run: |
          echo "Checking Haskell Stack installation..."
          stack --version
          echo "Checking GHC availability..."
          stack exec -- ghc --version || echo "GHC will be installed by Stack when needed"

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('**/*.yaml') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build project
        run: |
          stack build --test --no-run-tests
          echo "✅ Build completed successfully on branch ${{ github.ref_name }}"

      - name: Run tests
        run: |
          stack test
          echo "All tests passed"

      - name: Build final binary (verification)
        run: |
          make re
          echo "Final binary created successfully"
          ls -la glados
