name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('**/*.yaml') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build project
        run: |
          make  re
          echo "Build completed successfully on branch ${{ github.ref_name }}"

      - name: Run tests
        run: |
          make tests_run
          echo "All tests passed"

      - name: Build final binary (verification)
        run: |
          make re
          echo "Final binary created successfully"
          ls -la glados
