name: Binary Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (optional - will auto-generate if empty)'
        required: false

jobs:
  build-and-release:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate automatic tag
        id: generate_tag
        run: |
          if [ -n "${{ github.event.inputs.tag_name }}" ]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            # Generate automatic version based on date and commit
            DATE=$(date +%Y.%m.%d)
            SHORT_SHA=$(git rev-parse --short HEAD)
            COMMIT_COUNT=$(git rev-list --count HEAD)
            TAG_NAME="v${DATE}-${COMMIT_COUNT}-${SHORT_SHA}"
            echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "Generated automatic tag: ${TAG_NAME}"
          fi
      
      - name: Install build dependencies and Haskell Stack
        run: |
          echo "Installing required build tools..."
          sudo apt-get update
          sudo apt-get install -y build-essential make curl
          
          echo "Installing Haskell Stack..."
          if ! command -v stack &> /dev/null; then
            curl -sSL https://get.haskellstack.org/ | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
            export PATH="$HOME/.local/bin:$PATH"
          else
            echo "Stack already installed"
          fi
          
          echo "Verifying Stack installation..."
          stack --version

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('**/*.yaml') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build binary
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make re
          
      - name: Optimize binary
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          # Strip debugging symbols to reduce size
          if command -v strip >/dev/null 2>&1; then
            strip glados || echo "Strip failed or not available"
          fi
          # Make sure binary is executable
          chmod +x glados

      - name: Verify binary
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ls -la glados
          echo "Binary size: $(du -h glados | cut -f1)"
          
      - name: Create Release and Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag_name }}
          name: GLaDOS Release ${{ steps.generate_tag.outputs.tag_name }}
          files: |
            ./glados
          body: |
            ## GLaDOS Lisp Interpreter
            
            **Release:** ${{ steps.generate_tag.outputs.tag_name }}
            **Commit:** `${{ github.sha }}`
            
            ### Download
            Download the `glados` binary below.
            
            ### Quick Start
            ```bash
            # Make executable and run
            chmod +x glados
            ./glados your_file.lisp
            ```
            
            ### Latest Changes
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false